#!/bin/bash
#
#apache installeerimisskript
#
#kontroll, kas apache pole juba paigaldatud
apache=$(dpkg-query -W -f='${Status}' apache2 2>/dev/null | grep -c "ok installed")
#tulemus on kas 0 või suurem positiivne täisarv
#kui on 0 siis teenus pole paigaldatud
if [ $apache -eq 0 ]; then
	echo "Installeerime apache2."
	apt-get install -y apache2;
#kui ridade arv on nullist erinev
elif [ $apache -eq 1 ]; then
	echo "apache2 on installeeritud."
fi
service apache2 status
